version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  hex-to-rgb:
    build: HEX-to-RGB
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hex-to-rgb.rule=PathPrefix(`/hex-to-rgb`)"
      - "traefik.http.routers.hex-to-rgb.middlewares=hex-to-rgb-stripprefix"
      - "traefik.http.services.hex-to-rgb.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.hex-to-rgb-stripprefix.stripprefix.prefixes=/hex-to-rgb"

#  <microservice-example-name>:
#    build: <microservice-example-name>
#    restart: "no"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.<microservice-example-name>.rule=PathPrefix(`/<microservice-example-name>`)"
#      - "traefik.http.routers.<microservice-example-name>.middlewares=<microservice-example-name>-stripprefix"
#      - "traefik.http.services.<microservice-example-name>.loadbalancer.server.port=3000"
#      - "traefik.http.middlewares.<microservice-example-name>-stripprefix.stripprefix.prefixes=/<microservice-example-name>"
